#配置mysql数据源
spring:
  datasource:
    username: root
    password: 181181@Lq
    url: jdbc:mysql://192.168.30.128:4006/gulimall_pms
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.3:8848
  # redis
  redis:
    host: 192.168.30.128
    port: 6379
    password: 181181@Lq
  application:
    name: gulimall-product
  # Spring Cache
  cache:
    type: redis  #缓存的类型
    redis:
      time-to-live: 60000   #过期时间，单位ms  即1min
      #use-key-prefix: true #使用key前缀
      #key-prefix: CACHE_ #key前缀，表明这是缓存，和redis中的其他数据分开
      cache-null-values: true  #是否缓存空值，防止缓存穿透

# 配置mysql  .xml文件路径
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml   # classpath*表示不只扫描自己的类路径，也包含引用其他jar包的类路径
  # 主键自增
  global-config:
    db-config:
      id-type: auto
#服务端口
server:
  port: 10000