#配置mysql数据源
spring:
  datasource:
    username: root
    password: 181181@Lq
    url: jdbc:mysql://192.168.30.128:4006/gulimall_pms
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848  # 127.0.0.1
  # redis
  redis:
    host: 192.168.30.128
    port: 6379
    password: 181181@Lq
  application:
    name: gulimall-product
  # Spring Cache
  cache:
    type: redis  #缓存的类型
    redis:
      time-to-live: 60000   #过期时间，单位ms  即1min
      #use-key-prefix: true #使用key前缀
      #key-prefix: CACHE_ #key前缀，表明这是缓存，和redis中的其他数据分开
      cache-null-values: true  #是否缓存空值，防止缓存穿透
  #rabbitMQ
  rabbitmq:
    host: 192.168.30.130 # 服务器ip
    port: 5672  # 端口
    virtual-host: /  # 虚拟主机
    username: guest  # 账号，guest为默认值，不用配置
    password: guest  # 密码，guest为默认值，不用配置
    publisher-confirm-type: correlated # 开启confirmCallback（消息抵达broker确认）
    publisher-returns: true #开启returnCallback（消息抵达队列确认）
    template:
      mandatory: true #只要抵达队列，优先以异步方式回调
    listener:
      simple:
        acknowledge-mode: manual # 消费者开启消息手动确认模式




# 配置mysql  .xml文件路径
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml   # classpath*表示不只扫描自己的类路径，也包含引用其他jar包的类路径
  # 主键自增
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1 # 配置全局逻辑删除规则
      logic-not-delete-value: 0
#服务端口
server:
  port: 10000
logging:
  level:
    com.atguigu.gulimall: debug


#线程池参数
gulimall:
  thread:
    core-pool-size: 50  #核心线程数
    maximum-pool-size: 200 #最大线程数
    keep-alive-time: 10 #休眠时长 ，单位s

