spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848   # 127.0.0.1:8848
    gateway:
      routes:
        - id: test-route1
          uri: https://www.baidu.com/
          predicates:
            - Query=url,baidu
        - id: test-route2
          uri: https://www.qq.com/
          predicates:
            - Query=url,qq

        # 负载均衡到gulimall-product
        - id: to-product
          uri: lb://gulimall-product  #路由到gulimall-product,必须引入spring-cloud-starter-loadbalancer依赖，否则会报503错误
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/product/?(?<segment>.*), /product/$\{segment} # /api/product/**  -> gulimall-product模块  /product/**

        # 负载均衡到gulimall-member
        - id: to-member
          uri: lb://gulimall-member
          predicates:
            - Path=/api/member/**
          filters:
            - RewritePath=/api/member/?(?<segment>.*), /member/$\{segment}

        # 负载均衡到gulimall-ware
        - id: to-ware
          uri: lb://gulimall-ware
          predicates:
            - Path=/api/ware/**
          filters:
            - RewritePath=/api/ware/?(?<segment>.*), /ware/$\{segment}

        # 负载均衡到gulimall-third-party
        - id: to-third-party
          uri: lb://gulimall-third-party  #路由到gulimall-third-party
          predicates:
            - Path=/api/thirdparty/**
          filters:
            - RewritePath=/api/thirdparty/?(?<segment>.*), /third-party/$\{segment}

        # 到renren-fast
        - id: to-renren-fast
          uri: lb://renren-fast  #路由到renren-fast
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/?(?<segment>.*), /renren-fast/$\{segment} # /api/**  -> /renren-fast/**


  application:
    name: gulimall-gateway
server:
  port: 8888
