#配置注册中心
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848  # 127.0.0.1

  application:
    name: gulimall-third-party

#服务端口
server:
  port: 12000
  servlet:
    context-path: /third-party  #所有接口uri添加前缀

#阿里云OSS存储
alibaba:
  oss:
    endpoint: oss-cn-shanghai.aliyuncs.com #Endpoint按实际Region填写。
    accessKeyId: LTAI5tFTTUWqBbq8F9zzvhVb  #OSS_ACCESS_KEY_ID
    accessKeySecret: 9EvG2ZhCor8ZutCWrccFzJLDtaxDtU #OSS_ACCESS_KEY_SECRET
    bucket: gulimall-qianglong  #bucket (OSS存储空间名字)