#配置mysql数据源
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848  # 127.0.0.1
      config:
        import-check:
          enabled: false

  application:
    name: gulimall-cart

  ackson:
    date-format: yyyy-MM-dd HH:mm:ss # 指定时间格式
  thymeleaf:
    cache: false #关闭thymeleaf缓存，方便开发期间看到实时效果
    #prefix: classpath:/static/

  session:
    store-type: redis #指定Session存在redis
  redis:
    host: 192.168.30.128
    port: 6379
    password: 181181@Lq


#服务端口
server:
  port: 16000
  servlet:
    session:
      timeout: 30m #session过期时间30min
logging:
  level:
    com.atguigu.product: debug


#线程池参数
gulimall:
  thread:
    core-pool-size: 50  #核心线程数
    maximum-pool-size: 200 #最大线程数
    keep-alive-time: 10 #休眠时长 ，单位s
